### ISSUE TITLE
报No static method loadLibrary错误

### ISSUE THREAD

**Issue by klgd** [NervJS/taro-native-shell#4]
编译运行时直接报错：
```
java.lang.NoSuchMethodError: No static method loadLibrary(Ljava/lang/String;)V in class Lcom/facebook/soloader/SoLoader; or its super classes (declaration of 'com.facebook.soloader.SoLoader' appears in /data/app/com.tarodemo-61beqQ6pvhXVeuMkNVDhdg==/split_lib_dependencies_apk.apk)
        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:18)
        at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
        at com.facebook.react.bridge.JSCJavaScriptExecutorFactory.create(JSCJavaScriptExecutorFactory.java:21)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:912)
        at java.lang.Thread.run(Thread.java:764)
```
网上找的解决办法
```
implementation 'com.facebook.fresco:fresco:1.9.0'
implementation 'com.facebook.fresco:animated-gif:1.9.0'
// IN CASE YOU NEED WEBP SUPPORT / MAKE SURE TO CHANGE THIS TOO TO 1.9.0
implementation 'com.facebook.fresco:animated-webp:1.9.0'
implementation 'com.facebook.fresco:webpsupport:1.9.0'
```
试了，无效

**Comment by LeonaYoung** [comment]
same issues

**Comment by LeonaYoung** [comment]
```
taro-native-shell/node_modules/expo-image-picker/android/build.gradle

77:  api 'com.facebook.fresco:fresco:1.10.0' 
```

改为 1.9.0 即可！@klgd

**Comment by Pines-Cheng** [comment]
RN 0.55.4 下 expo-image-picker 的问题，已经提了 issue，但是貌似他们不打算修复。https://github.com/expo/expo/issues/4990

**Comment by klgd** [comment]
ok
