### ISSUE TITLE
vivo上架，提示 存在收集个人信息（(SDK: FaceBookReact) 读取设备IP）的行为。如何解决

### ISSUE THREAD

**Issue by reshub-ai** [NervJS/taro-native-shell#87]
vivo 上架安卓应用，被驳回，反馈如下：

未经用户同意，存在收集个人信息（(SDK: FaceBookReact) 读取设备IP）的行为。

如何处理？

**Comment by zhiqingchen** [comment]
看堆栈信息，找到调用位置，禁用

**Comment by reshub-ai** [comment]
业务没提供堆栈，我确认一下

**Comment by reshub-ai** [comment]
at java.net.NetworkInterface.getInetAddresses()
 at com.reactnativecommunity.netinfo.ConnectivityReceiver.createDetailsMap(ConnectivityReceiver.java:196)
 at com.reactnativecommunity.netinfo.ConnectivityReceiver.createConnectivityEventMap(ConnectivityReceiver.java:165)
 at com.reactnativecommunity.netinfo.ConnectivityReceiver.getCurrentState(ConnectivityReceiver.java:90)
 at com.reactnativecommunity.netinfo.NetInfoModule.getCurrentState(NetInfoModule.java:58)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
 at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
 at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
 at android.os.Looper.loop(Looper.java:164)
 at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
 at java.lang.Thread.run(Thread.java:764)

你好，这个是堆栈，查了一下是taro-rn的依赖库 react-native-community/netinfo，现在我需要如何处理呢，项目里没有主动调用获取ip，谢谢

"@tarojs/taro-rn@3.5.11":
  version "3.5.11"
  resolved "https://registry.npmmirror.com/@tarojs/taro-rn/-/taro-rn-3.5.11.tgz#ce900a39c8c0e245867f37785074c12ded26f70a"
  integrity sha512-6V06hKMsylMj2ODrcsK4V2OnozYUT3bTqmTz5IrG/PgHrf+SmZrFUf0+z335gtNBtecOgF/FG0i/fBiHtD96/Q==
  dependencies:
    "@react-native-async-storage/async-storage" "~1.17.7"
    "@react-native-community/cameraroll" "~4.1.2"
    "@react-native-community/clipboard" "~1.5.1"
    "@react-native-community/geolocation" "~2.1.0"
    **"@react-native-community/netinfo" "~9.3.0"**
    "@tarojs/runtime-rn" "3.5.11"
    babel-preset-expo "~9.2.0"
    base64-js "^1.3.0"
    deprecated-react-native-prop-types "^2.3.0"
    expo-av "~12.0.3"
    expo-barcode-scanner "~11.4.0"
    expo-brightness "~10.3.0"
    expo-camera "~12.3.0"
    expo-file-system "~14.1.0"
    expo-image-picker "~13.3.1"
    expo-keep-awake "~10.2.0"
    expo-location "~14.3.0"
    expo-modules-core "~0.11.3"
    expo-sensors "~11.4.0"
    nullthrows "^1.1.1"
    prop-types "^15.8.1"
    react-native-device-info "~10.0.2"
    react-native-image-resizer "~1.4.5"
    react-native-image-zoom-viewer "^3.0.1"
    react-native-root-siblings "^4.1.1"
    react-native-root-toast "^3.0.1"
    react-native-safe-area-context "~4.3.1"
    react-native-stylekit "^1.0.0"
    react-native-syan-image-picker "0.5.3"

**Comment by zhiqingchen** [comment]
### 查看是否使用到如下方法
onNetworkStatusChange
getNetworkType

### taro rn 中确认不使用的依赖可以删除的。

**Comment by reshub-ai** [comment]
感谢，查了一下调用了getNetworkType，做个判断再请求了

**Comment by reshub-ai** [comment]
另外我把 依赖 react-native-community/netinfo 删除了，执行yarn之后又自动添加了，是否和我调用了getNetworkType有关呢
