### ISSUE TITLE
关于壳工程打包问题

### ISSUE THREAD

**Issue by kunkuntang** [NervJS/taro-native-shell#89]
壳工程 分支 0.70.0 代码：

1. 先使用壳工程安装了 debug 版本的 app，然后在 源工程 `yarn dev:rn` 进行开发调试
2. 开发完毕后在 源工程 配置好 output 路径，然后执行 `yarn build:rn --platform android` 打包
3. 回到壳工程执行 `cd android && ./gradlew assembleRelease` 打包 apk 文件。

发现打包出来的 apk 是壳工程里的示例代码，把 壳工程 的 [App.js 文件名](https://github.com/NervJS/taro-native-shell/blob/0.70.0/App.js)修改成 App3.js 后再次执行上述的打包步骤，发现出现了如下报错：

```
error Unable to resolve module ./App from /Volumes/KINGSTON_DISK/www/taro-app-shell/index.js: 

Error: Unable to resolve module ./App from /Volumes/KINGSTON_DISK/www/taro-app-shell/index.js: 

None of these files exist:
  * App(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * App/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  4 |
None of these files exist:
  * App(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * App/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  5 | import {AppRegistry} from 'react-native';
> 6 | import App from './App';
    |                  ^
  7 | import {name as appName} from './app.json';
  8 |
  9 | AppRegistry.registerComponent(appName, () => App);.
  4 |
  5 | import {AppRegistry} from 'react-native';
> 6 | import App from './App';
    |                  ^
  7 | import {name as appName} from './app.json';
  8 |
  9 | AppRegistry.registerComponent(appName, () => App);
    at ModuleResolver.resolveDependency (/Volumes/KINGSTON_DISK/www/taro-app-shell/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:152:15)
    at DependencyGraph.resolveDependency (/Volumes/KINGSTON_DISK/www/taro-app-shell/node_modules/metro/src/node-haste/DependencyGraph.js:264:43)
    at Object.resolve (/Volumes/KINGSTON_DISK/www/taro-app-shell/node_modules/metro/src/lib/transformHelpers.js:170:21)
    at resolveDependencies (/Volumes/KINGSTON_DISK/www/taro-app-shell/node_modules/metro/src/DeltaBundler/graphOperations.js:466:33)
    at processModule (/Volumes/KINGSTON_DISK/www/taro-app-shell/node_modules/metro/src/DeltaBundler/graphOperations.js:232:31)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async traverseDependenciesForSingleFile (/Volumes/KINGSTON_DISK/www/taro-app-shell/node_modules/metro/src/DeltaBundler/graphOperations.js:221:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (/Volumes/KINGSTON_DISK/www/taro-app-shell/node_modules/metro/src/DeltaBundler/graphOperations.js:204:3)
    at async DeltaCalculator._getChangedDependencies (/Volumes/KINGSTON_DISK/www/taro-app-shell/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:208:25)
info Run CLI with --verbose flag for more details.

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 1m 11s
799 actionable tasks: 31 executed, 768 up-to-date
```

可以发现在 壳工程 执行打包 apk 命令时会再次执行类似 `yarn build:rn --platform android` 的行为，从而把我从源工程打包的文件覆盖掉。请问有什么办法解决吗？

**Comment by zhiqingchen** [comment]
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

这一行注释掉

**Comment by kunkuntang** [comment]
> apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
> 
> 这一行注释掉

注释掉后，打包报一下错误了

```
/Volumes/KINGSTON_DISK/www/taro-app-shell/android/app/src/main/java/com/tarodemo/MainActivity.java:2: error: package expo.modules does not exist
import expo.modules.ReactActivityDelegateWrapper;
                   ^
/Volumes/KINGSTON_DISK/www/taro-app-shell/android/app/src/main/java/com/tarodemo/MainApplication.java:3: error: package expo.modules does not exist
import expo.modules.ApplicationLifecycleDispatcher;
                   ^
/Volumes/KINGSTON_DISK/www/taro-app-shell/android/app/src/main/java/com/tarodemo/MainApplication.java:4: error: package expo.modules does not exist
import expo.modules.ReactNativeHostWrapper;
                   ^
/Volumes/KINGSTON_DISK/www/taro-app-shell/android/app/src/main/java/com/tarodemo/MainApplication.java:8: error: cannot find symbol
import com.facebook.react.PackageList;
                         ^
  symbol:   class PackageList
  location: package com.facebook.react
/Volumes/KINGSTON_DISK/www/taro-app-shell/android/app/src/main/java/com/tarodemo/newarchitecture/MainApplicationReactNativeHost.java:5: error: cannot find symbol
import com.facebook.react.PackageList;
                         ^
  symbol:   class PackageList
  location: package com.facebook.react
/Volumes/KINGSTON_DISK/www/taro-app-shell/android/app/src/main/java/com/tarodemo/MainActivity.java:26: error: cannot find symbol
    return new ReactActivityDelegateWrapper(this, new MainActivityDelegate(this, getMainComponentName()));
               ^
  symbol:   class ReactActivityDelegateWrapper
  location: class MainActivity
/Volumes/KINGSTON_DISK/www/taro-app-shell/android/app/src/main/java/com/tarodemo/MainApplication.java:22: error: cannot find symbol
      new ReactNativeHostWrapper(this, new ReactNativeHost(this) {
          ^
  symbol:   class ReactNativeHostWrapper
  location: class MainApplication
/Volumes/KINGSTON_DISK/www/taro-app-shell/android/app/src/main/java/com/tarodemo/MainApplication.java:31: error: cannot find symbol
          List<ReactPackage> packages = new PackageList(this).getPackages();
                                            ^
  symbol: class PackageList
/Volumes/KINGSTON_DISK/www/taro-app-shell/android/app/src/main/java/com/tarodemo/MainApplication.java:44: error: cannot find symbol
      new ReactNativeHostWrapper(this, new MainApplicationReactNativeHost(this));
          ^
  symbol:   class ReactNativeHostWrapper
  location: class MainApplication
/Volumes/KINGSTON_DISK/www/taro-app-shell/android/app/src/main/java/com/tarodemo/MainApplication.java:62: error: cannot find symbol
    ApplicationLifecycleDispatcher.onApplicationCreate(this);
    ^
  symbol:   variable ApplicationLifecycleDispatcher
  location: class MainApplication
/Volumes/KINGSTON_DISK/www/taro-app-shell/android/app/src/main/java/com/tarodemo/MainApplication.java:99: error: cannot find symbol
    ApplicationLifecycleDispatcher.onConfigurationChanged(this, newConfig);
    ^
  symbol:   variable ApplicationLifecycleDispatcher
  location: class MainApplication
/Volumes/KINGSTON_DISK/www/taro-app-shell/android/app/src/main/java/com/tarodemo/newarchitecture/MainApplicationReactNativeHost.java:47: error: cannot find symbol
    List<ReactPackage> packages = new PackageList(this).getPackages();
                                      ^
  symbol:   class PackageList
  location: class MainApplicationReactNativeHost
12 errors

> Task :app:compileReleaseJavaWithJavac FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileReleaseJavaWithJavac'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)

```

**Comment by kunkuntang** [comment]
> apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
> 
> 这一行注释掉

改成注释掉 `android/app/build.gradle` 文件中的下面一行代码后可以成功打包，但是安装apk后会闪退

[// apply from: "../../node_modules/react-native/react.gradle"](https://github.com/kunkuntang/taro-native-shell/blob/0.70.0/android/app/build.gradle#L85)

**Comment by blackboyhc** [comment]
> > apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
> > 这一行注释掉
> 
> 改成注释掉 `android/app/build.gradle` 文件中的下面一行代码后可以成功打包，但是安装apk后会闪退
> 
> [// apply from: "../../node_modules/react-native/react.gradle"](https://github.com/kunkuntang/taro-native-shell/blob/0.70.0/android/app/build.gradle#L85)

@kunkuntang  这个问题解决了吗

**Comment by Ccc437647** [comment]
老哥,你这个问题解决了吗?我通过壳文件打出来的debug.apk 是我的工程代码, 但是打包出来的release.apk却是官方demo
